### ISSUE TITLE
Link spans do not respect sampling configuration

### ISSUE THREAD

**Issue by DanielHeath** [carwow/honeykiq#17]
It'd be good to have some way to avoid sending a link span if you sample out the job span. 

As it stands the link mode is unusable if you have any real volume, because it gets sent even if neither the span for the job nor the enqueuing request is being sent.

**Comment by PChambino** [comment]
Hi @DanielHeath! That is a very good point. We are adding the event directly to the libhoney client ([line](https://github.com/carwow/honeykiq/blob/de2115cb19909cba79ad465601f4e40416fa752c/lib/honeykiq/beeline_span.rb#L39)). Not sure if there was a reason for that, but I guess it should be added to the current span instead, so that it is sent together with that span. Would be able to open a PR for that?

**Comment by PChambino** [comment]
This has been fixed on https://github.com/carwow/honeykiq/commit/2a16f7d25b3ee55e942474ed29ed7e0d5b289f86

Link events now respect beeline sampling on the server middleware. However, because it is linking two traces, the probability of one of the traces being sampled out is high, making the link event not always useful.

Depending on your use case, my suggestion is to include a field in the serialized trace data with an identifiable name (e.g. `parent.name: HomeController#index`) of the parent trace. Usually that is enough to understand what is enqueuing jobs. (Currently not supported by honeykiq out of the box, so it would require custom code.)
